apiVersion: v1
kind: Pod
metadata:
  name: podman
spec:
 containers:
 - name: conman
   image: redis
   volumeMounts:
   - name: volume1
     mountPath: /tmp/
 volumes:
 - name: volume1
   configMap:
     name: cf-map
      
